name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.8
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus:
    #path: ../notus/
    git:
      url: git://github.com/beerstorm-net/zefyr.git
      path: packages/notus/
  quill_delta: ^1.0.2
  html: ^0.14.0

dev_dependencies:
  test:
